import { jsPDF } from "jspdf";
import { format, parse } from "date-fns";

export interface ReportPdfData {
  report_month: string; // yyyy-MM or yyyy-MM-dd..yyyy-MM-dd
  total_mentions: number;
  positives: number;
  negatives: number;
  neutrals: number;
  top_sources: string[];
  created_at?: string;
}

export async function downloadReportPdf(report: ReportPdfData) {
  const doc = new jsPDF({ unit: 'pt', format: 'a4' });
  const margin = 48;
  let y = margin;

  let periodText = report.report_month;
  if (/^\d{4}-\d{2}$/.test(report.report_month)) {
    const monthDate = parse(`${report.report_month}-01`, 'yyyy-MM-dd', new Date());
    periodText = format(monthDate, 'LLLL yyyy');
  } else if (/^\d{4}-\d{2}-\d{2}\.\.\d{4}-\d{2}-\d{2}$/.test(report.report_month)) {
    const [s, e] = report.report_month.split('..');
    const sd = parse(s, 'yyyy-MM-dd', new Date());
    const ed = parse(e, 'yyyy-MM-dd', new Date());
    periodText = `${format(sd, 'PPP')} – ${format(ed, 'PPP')}`;
  }

  // Title
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(18);
  doc.text(`Brand Monitoring Report`, margin, y);
  y += 24;
  doc.setFont('helvetica', 'normal');
  doc.setFontSize(12);
  doc.text(`Period: ${periodText}`, margin, y);
  y += 18;
  if (report.created_at) {
    const created = format(new Date(report.created_at), 'PPP');
    doc.text(`Generated on: ${created}`, margin, y);
    y += 18;
  }

  // Divider
  doc.setDrawColor(180);
  doc.line(margin, y, 595 - margin, y);
  y += 24;

  // Metrics
  doc.setFont('helvetica', 'bold');
  doc.text('Key Metrics', margin, y);
  y += 18;
  doc.setFont('helvetica', 'normal');
  doc.text(`Total Mentions: ${report.total_mentions}`, margin, y);
  y += 16;
  doc.text(`Positive: ${report.positives}`, margin, y);
  y += 16;
  doc.text(`Neutral: ${report.neutrals}`, margin, y);
  y += 16;
  doc.text(`Negative: ${report.negatives}`, margin, y);
  y += 24;

  // Simple bars visualization
  const maxVal = Math.max(1, report.total_mentions);
  const barWidthMax = 300;
  const barHeight = 12;

  const drawBar = (label: string, value: number, offset: number) => {
    const width = Math.max(1, (value / maxVal) * barWidthMax);
    doc.setFillColor(60 + offset, 130, 200 - offset);
    doc.rect(margin, y, width, barHeight, 'F');
    doc.text(`${label}: ${value}`, margin + barWidthMax + 12, y + barHeight - 2);
    y += barHeight + 8;
  };

  doc.setFont('helvetica', 'bold');
  doc.text('Distribution', margin, y);
  y += 16;
  doc.setFont('helvetica', 'normal');
  drawBar('Positive', report.positives, 0);
  drawBar('Neutral', report.neutrals, 40);
  drawBar('Negative', report.negatives, 80);
  y += 8;

  // Top sources
  doc.setFont('helvetica', 'bold');
  doc.text('Top Sources', margin, y);
  y += 16;
  doc.setFont('helvetica', 'normal');
  if (report.top_sources && report.top_sources.length) {
    report.top_sources.forEach((src, i) => {
      doc.text(`${i + 1}. ${src}`, margin, y);
      y += 16;
    });
  } else {
    doc.text('No top sources available for this period.', margin, y);
    y += 16;
  }

  // Footer
  const pageHeight = doc.internal.pageSize.getHeight();
  doc.setFontSize(9);
  doc.setTextColor(120);
  doc.text('Generated by your Brand Monitoring Dashboard', margin, pageHeight - 24);

  doc.save(`brand-report-${report.report_month}.pdf`);
}

