project_id = "sjypzdqelypxymzzxhxi"

[api]
enabled = true
port = 54321
schemas = ["public", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[db]
port = 54322

[db.pooler]
enabled = false
port = 54329
pool_mode = "transaction"
default_pool_size = 20
max_client_conn = 100

[realtime]
enabled = true
ip_version = "IPv4"

[studio]
enabled = true
port = 54323
api_url = "http://127.0.0.1:54321"

[inbucket]
enabled = true
port = 54324
smtp_port = 1100
pop3_port = 1110

[storage]
enabled = true
file_size_limit = "50MiB"
image_transformation = { enabled = true }

[auth]
enabled = true
site_url = "http://127.0.0.1:3000"
additional_redirect_urls = ["https://lovable.dev"]
jwt_expiry = 3600
enable_signup = true

[auth.email]
enable_signup = true
double_confirm_changes = true
enable_confirmations = false

[functions.brand-monitor]
verify_jwt = true

[functions.monitor-news]
verify_jwt = false

[functions.aggregate-sources]
verify_jwt = false

[functions.google-alerts]
verify_jwt = true

[functions.notify-n8n-new-mention]
enabled = true
verify_jwt = true
import_map = "./functions/notify-n8n-new-mention/deno.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/notify-n8n-new-mention/index.ts"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/notify-n8n-new-mention/*.html" ]
