import React from 'react';
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card';
import { Button } from '@/components/ui/button';
import { ArrowLeft } from 'lucide-react';
import { useNavigate } from 'react-router-dom';

const PrivacyPolicy = () => {
  const navigate = useNavigate();

  const handleGoBack = () => {
    navigate(-1);
  };

  return (
    <div className="min-h-screen bg-background p-4">
      <div className="max-w-4xl mx-auto">
        <div className="mb-6">
          <Button 
            variant="ghost" 
            onClick={handleGoBack}
            className="mb-4"
          >
            <ArrowLeft className="h-4 w-4 mr-2" />
            Back
          </Button>
          <h1 className="text-3xl font-bold">Privacy Policy</h1>
          <p className="text-muted-foreground mt-2">
            Last updated: {new Date().toLocaleDateString('en-US', { 
              year: 'numeric', 
              month: 'long', 
              day: 'numeric' 
            })}
          </p>
        </div>

        <div className="space-y-6">
          <Card>
            <CardHeader>
              <CardTitle>1. Information We Collect</CardTitle>
            </CardHeader>
            <CardContent className="space-y-4">
              <div>
                <h3 className="font-semibold mb-2">Personal Information</h3>
                <ul className="list-disc list-inside space-y-1 text-sm text-muted-foreground">
                  <li>Email address (required for account creation and notifications)</li>
                  <li>Full name (optional, for personalized communications)</li>
                  <li>Phone number (optional, for SMS notifications if enabled)</li>
                  <li>Team email addresses (PR team, legal team - optional)</li>
                </ul>
              </div>
              
              <div>
                <h3 className="font-semibold mb-2">Brand Monitoring Data</h3>
                <ul className="list-disc list-inside space-y-1 text-sm text-muted-foreground">
                  <li>Brand keywords and monitoring terms you configure</li>
                  <li>Mention content collected from public sources (social media, news, etc.)</li>
                  <li>Sentiment analysis results generated by AI</li>
                  <li>Source URLs and publication dates of mentions</li>
                </ul>
              </div>

              <div>
                <h3 className="font-semibold mb-2">Usage Information</h3>
                <ul className="list-disc list-inside space-y-1 text-sm text-muted-foreground">
                  <li>Account activity and login sessions</li>
                  <li>Feature usage and preferences</li>
                  <li>Notification preferences and delivery logs</li>
                  <li>API usage for quota management</li>
                </ul>
              </div>

              <div>
                <h3 className="font-semibold mb-2">Technical Information</h3>
                <ul className="list-disc list-inside space-y-1 text-sm text-muted-foreground">
                  <li>IP address and browser information</li>
                  <li>Device and operating system details</li>
                  <li>Application performance metrics</li>
                  <li>Error logs for system improvement</li>
                </ul>
              </div>
            </CardContent>
          </Card>

          <Card>
            <CardHeader>
              <CardTitle>2. How We Use Your Information</CardTitle>
            </CardHeader>
            <CardContent className="space-y-4">
              <div>
                <h3 className="font-semibold mb-2">Service Delivery</h3>
                <ul className="list-disc list-inside space-y-1 text-sm text-muted-foreground">
                  <li>Monitor brand mentions across public platforms</li>
                  <li>Analyze sentiment of mentions using AI technology</li>
                  <li>Send notifications about relevant brand mentions</li>
                  <li>Generate analytics and reports on brand reputation</li>
                </ul>
              </div>

              <div>
                <h3 className="font-semibold mb-2">Communication</h3>
                <ul className="list-disc list-inside space-y-1 text-sm text-muted-foreground">
                  <li>Send email notifications for negative sentiment mentions</li>
                  <li>Provide service updates and system notifications</li>
                  <li>Respond to support requests and inquiries</li>
                  <li>Send optional SMS notifications if enabled</li>
                </ul>
              </div>

              <div>
                <h3 className="font-semibold mb-2">Service Improvement</h3>
                <ul className="list-disc list-inside space-y-1 text-sm text-muted-foreground">
                  <li>Analyze usage patterns to improve features</li>
                  <li>Monitor system performance and reliability</li>
                  <li>Debug technical issues and errors</li>
                  <li>Develop new features and capabilities</li>
                </ul>
              </div>

              <div>
                <h3 className="font-semibold mb-2">Security and Compliance</h3>
                <ul className="list-disc list-inside space-y-1 text-sm text-muted-foreground">
                  <li>Authenticate users and prevent unauthorized access</li>
                  <li>Monitor for security threats and suspicious activity</li>
                  <li>Comply with legal obligations and regulations</li>
                  <li>Enforce terms of service and acceptable use policies</li>
                </ul>
              </div>
            </CardContent>
          </Card>

          <Card>
            <CardHeader>
              <CardTitle>3. Data Sources and Collection Methods</CardTitle>
            </CardHeader>
            <CardContent className="space-y-4">
              <div>
                <h3 className="font-semibold mb-2">Public Data Sources</h3>
                <ul className="list-disc list-inside space-y-1 text-sm text-muted-foreground">
                  <li><strong>Social Media:</strong> X (Twitter), Reddit, YouTube (public posts and comments)</li>
                  <li><strong>News and Media:</strong> RSS feeds, Google Alerts, news websites</li>
                  <li><strong>Public Forums:</strong> Discussion boards, community platforms</li>
                  <li><strong>Review Sites:</strong> Public review and rating platforms</li>
                </ul>
              </div>

              <div>
                <h3 className="font-semibold mb-2">Collection Methods</h3>
                <ul className="list-disc list-inside space-y-1 text-sm text-muted-foreground">
                  <li>Automated web scraping of public content</li>
                  <li>API integrations with third-party platforms</li>
                  <li>RSS feed monitoring and parsing</li>
                  <li>Search engine alerts and notifications</li>
                </ul>
              </div>

              <div className="bg-yellow-50 border border-yellow-200 rounded-lg p-4">
                <h3 className="font-semibold mb-2 text-yellow-800">Important Note</h3>
                <p className="text-sm text-yellow-700">
                  We only collect data from publicly available sources. We do not access private accounts, 
                  protected posts, or any content that requires authentication or special permissions.
                </p>
              </div>
            </CardContent>
          </Card>

          <Card>
            <CardHeader>
              <CardTitle>4. Data Sharing and Third-Party Services</CardTitle>
            </CardHeader>
            <CardContent className="space-y-4">
              <div>
                <h3 className="font-semibold mb-2">Service Providers</h3>
                <ul className="list-disc list-inside space-y-1 text-sm text-muted-foreground">
                  <li><strong>Supabase:</strong> Database hosting and authentication services</li>
                  <li><strong>SendGrid:</strong> Email delivery and notification services</li>
                  <li><strong>Twilio:</strong> SMS and WhatsApp notification services (optional)</li>
                  <li><strong>OpenAI:</strong> AI-powered sentiment analysis and content processing</li>
                  <li><strong>Vercel:</strong> Application hosting and deployment platform</li>
                </ul>
              </div>

              <div>
                <h3 className="font-semibold mb-2">Data Processing</h3>
                <p className="text-sm text-muted-foreground mb-2">
                  We may share your data with these service providers only as necessary to deliver our services. 
                  All third-party providers are bound by strict data protection agreements and industry-standard security practices.
                </p>
              </div>

              <div>
                <h3 className="font-semibold mb-2">No Sale of Data</h3>
                <p className="text-sm text-muted-foreground">
                  We do not sell, rent, or trade your personal information to third parties for marketing purposes.
                </p>
              </div>
            </CardContent>
          </Card>

          <Card>
            <CardHeader>
              <CardTitle>5. Data Security and Storage</CardTitle>
            </CardHeader>
            <CardContent className="space-y-4">
              <div>
                <h3 className="font-semibold mb-2">Security Measures</h3>
                <ul className="list-disc list-inside space-y-1 text-sm text-muted-foreground">
                  <li>Encryption in transit and at rest using industry-standard protocols</li>
                  <li>Secure authentication and session management</li>
                  <li>Regular security audits and vulnerability assessments</li>
                  <li>Access controls and role-based permissions</li>
                  <li>Automated backup and disaster recovery systems</li>
                </ul>
              </div>

              <div>
                <h3 className="font-semibold mb-2">Data Retention</h3>
                <ul className="list-disc list-inside space-y-1 text-sm text-muted-foreground">
                  <li>Account data: Retained while your account is active</li>
                  <li>Mention data: Retained for the duration of your subscription</li>
                  <li>Logs and analytics: Retained for up to 2 years for system improvement</li>
                  <li>Deleted data: Permanently removed from all systems within 30 days</li>
                </ul>
              </div>
            </CardContent>
          </Card>

          <Card>
            <CardHeader>
              <CardTitle>6. Your Rights and Choices</CardTitle>
            </CardHeader>
            <CardContent className="space-y-4">
              <div>
                <h3 className="font-semibold mb-2">Account Management</h3>
                <ul className="list-disc list-inside space-y-1 text-sm text-muted-foreground">
                  <li>Update your personal information at any time</li>
                  <li>Modify notification preferences and frequency</li>
                  <li>Change or remove monitoring keywords and settings</li>
                  <li>Access your data and export it if needed</li>
                </ul>
              </div>

              <div>
                <h3 className="font-semibold mb-2">Communication Preferences</h3>
                <ul className="list-disc list-inside space-y-1 text-sm text-muted-foreground">
                  <li>Unsubscribe from email notifications</li>
                  <li>Disable SMS notifications</li>
                  <li>Choose notification frequency (immediate, daily, weekly)</li>
                  <li>Opt out of non-essential communications</li>
                </ul>
              </div>

              <div>
                <h3 className="font-semibold mb-2">Data Rights</h3>
                <ul className="list-disc list-inside space-y-1 text-sm text-muted-foreground">
                  <li>Request access to your personal data</li>
                  <li>Request correction of inaccurate information</li>
                  <li>Request deletion of your account and associated data</li>
                  <li>Request data portability in a structured format</li>
                </ul>
              </div>
            </CardContent>
          </Card>

          <Card>
            <CardHeader>
              <CardTitle>7. Cookies and Tracking</CardTitle>
            </CardHeader>
            <CardContent className="space-y-4">
              <div>
                <h3 className="font-semibold mb-2">Essential Cookies</h3>
                <ul className="list-disc list-inside space-y-1 text-sm text-muted-foreground">
                  <li>Authentication and session management</li>
                  <li>User preferences and settings</li>
                  <li>Security and fraud prevention</li>
                  <li>Application functionality and performance</li>
                </ul>
              </div>

              <div>
                <h3 className="font-semibold mb-2">Analytics and Monitoring</h3>
                <ul className="list-disc list-inside space-y-1 text-sm text-muted-foreground">
                  <li>Application performance monitoring</li>
                  <li>Error tracking and debugging</li>
                  <li>Usage analytics for service improvement</li>
                  <li>No personal data is collected for analytics</li>
                </ul>
              </div>
            </CardContent>
          </Card>

          <Card>
            <CardHeader>
              <CardTitle>8. International Data Transfers</CardTitle>
            </CardHeader>
            <CardContent>
              <p className="text-sm text-muted-foreground mb-4">
                Your data may be processed and stored in servers located outside your country of residence. 
                We ensure that all international data transfers comply with applicable data protection laws 
                and implement appropriate safeguards to protect your information.
              </p>
              
              <div className="bg-blue-50 border border-blue-200 rounded-lg p-4">
                <h3 className="font-semibold mb-2 text-blue-800">Data Processing Locations</h3>
                <ul className="list-disc list-inside space-y-1 text-sm text-blue-700">
                  <li>Primary hosting: United States (Vercel, Supabase)</li>
                  <li>Email services: United States (SendGrid)</li>
                  <li>AI processing: United States (OpenAI)</li>
                  <li>CDN and performance: Global distribution</li>
                </ul>
              </div>
            </CardContent>
          </Card>

          <Card>
            <CardHeader>
              <CardTitle>9. Children's Privacy</CardTitle>
            </CardHeader>
            <CardContent>
              <p className="text-sm text-muted-foreground">
                Our service is not intended for individuals under 16 years of age. We do not knowingly 
                collect personal information from children under 16. If you become aware that a child 
                has provided us with personal information, please contact us immediately.
              </p>
            </CardContent>
          </Card>

          <Card>
            <CardHeader>
              <CardTitle>10. Changes to This Privacy Policy</CardTitle>
            </CardHeader>
            <CardContent>
              <p className="text-sm text-muted-foreground">
                We may update this Privacy Policy from time to time. We will notify you of any material 
                changes by email or through a notice on our service. Your continued use of the service 
                after any modifications constitutes acceptance of the updated Privacy Policy.
              </p>
            </CardContent>
          </Card>

          <Card>
            <CardHeader>
              <CardTitle>11. Contact Information</CardTitle>
            </CardHeader>
            <CardContent className="space-y-4">
              <div>
                <h3 className="font-semibold mb-2">Privacy Questions</h3>
                <p className="text-sm text-muted-foreground">
                  If you have any questions about this Privacy Policy or our data practices, please contact us:
                </p>
              </div>
              
              <div className="bg-gray-50 rounded-lg p-4">
                <ul className="space-y-2 text-sm">
                  <li><strong>Email:</strong> privacy@reputations.io</li>
                  <li><strong>Support:</strong> Available through your account dashboard</li>
                  <li><strong>Data Requests:</strong> Use the contact methods above for data access, correction, or deletion requests</li>
                </ul>
              </div>
            </CardContent>
          </Card>
        </div>
      </div>
    </div>
  );
};

export default PrivacyPolicy;
