// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://sjypzdqelypxymzzxhxi.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNqeXB6ZHFlbHlweHltenp4aHhpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQ1ODQ4NjQsImV4cCI6MjA3MDE2MDg2NH0.HkMy1dRyXSyiSOgpplZMGFWOoMbMXJ73kLWWCd_KcRQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});